config/routes.rb
Rails.application.routes.draw do
  # Health Check Route
  get "up" => "rails/health#show", as: :rails_health_check

  # Default route
  root to: "home#show"

  # Pokemon Routes
  resources :pokemons, only: [:index, :show]

  # PWA Routes
  get "service-worker.js", to: "pwa#service_worker"
  get "manifest.json", to: "pwa#manifest"

  # config/routes.rb
  direct :cdn_image do |model, options|
    if Rails.env.production?
      expires_in = options.delete(:expires_in) { ActiveStorage.urls_expire_in }

      if model.respond_to?(:signed_id)
        route_for(
          :rails_service_blob_proxy,
          model.signed_id(expires_in: expires_in),
          model.filename,
          options.merge(host: Rails.application.credentials.dig(:cdn, :host))
        )
      else
        signed_blob_id = model.blob.signed_id(expires_in: expires_in)
        variation_key  = model.variation.key
        filename       = model.blob.filename

        route_for(
          :rails_blob_representation_proxy,
          signed_blob_id,
          variation_key,
          filename,
          options.merge(host: Rails.application.credentials.dig(:cdn, :host))
        )
      end
    else
      rails_blob_url(model, options)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
require "open-uri"
require 'csv'

class Pokemon < ApplicationRecord
  include Pokemon::Importable

  IMPORTING_MAP = [
    %w[id id],
    %w[identifier name],
    %w[order order],
    %w[species_id species_id],
  ].freeze

  IMPORTING_FILE_NAME = 'pokemon.csv'.freeze

  # Association for the Pokémon it can evolve into (multiple evolutions)
  has_many :evolutions, class_name: 'Pokemon', foreign_key: 'evolves_from_id'

  # Association for the Pokémon it evolved from
  belongs_to :pre_evolution, class_name: 'Pokemon', foreign_key: 'evolves_from_id', optional: true

  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_stats
  has_many :stats, through: :pokemon_stats

  has_one_attached :default_sprite
  has_one_attached :front_default_sprite

  class << self
    def import_descriptions
      pokemon_species_flavor_text_file = File.read(Rails.root.join('db', 'pokemon_csvs', 'pokemon_species_flavor_text.csv'))
      pokemon_species_flavor_text = CSV.parse(pokemon_species_flavor_text_file, headers: true)
      pokemon_species_flavor_text.each do |row|
        next unless row['language_id'] == '9'

        if (pokemon = Pokemon.find_by(species_id: row['species_id']))
          pokemon.update(description: row['flavor_text'])
        end
      end
    end

    def set_evolves_from
      pokemon_species = File.read(Rails.root.join('db', 'pokemon_csvs', 'pokemon_species.csv'))
      pokemon_species = CSV.parse(pokemon_species, headers: true)
      pokemon_species.each do |row|
        if (pokemon = Pokemon.find_by(name: row['identifier']))
          next unless row['evolves_from_species_id'].present?
          pokemon.update!(evolves_from_id: Pokemon.order(:id).find_by(species_id: row['evolves_from_species_id']).id)
        end
      end
    end
  end

  def attach_default_sprite_later
    Pokemon::AttachSpriteJob.perform_later(self)
  end

  def attach_default_sprite
    default_sprite.purge if default_sprite.attached?
    sprite_uri = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/#{id}.png"
    default_sprite.attach(io: URI.parse(sprite_uri).open, filename: "#{id}_default_sprite.png" )
  end

  def full_evolution_chain
    base_form = find_base_form
    chain = [[base_form]]
    base_form.build_evolution_chain(chain, 1)
    chain.reject(&:empty?)
  end

  def build_evolution_chain(chain, level)
    chain[level] ||= []
    evolutions.each do |evolution|
      chain[level] << evolution
      evolution.build_evolution_chain(chain, level + 1)
    end
  end

  def find_base_form
    current_pokemon = self
    while current_pokemon.pre_evolution.present?
      current_pokemon = current_pokemon.pre_evolution
    end
    current_pokemon
  end
end

app/models/pokemon/importable.rb
module Pokemon::Importable
  extend ActiveSupport::Concern

  included do
    def self.import_from_csv
      records = []

      CSV.read(
        Rails.root.join('db', 'pokemon_csvs', self::IMPORTING_FILE_NAME),
        headers: true
      ).each do |row|
        records << {}.tap do |record|
          self::IMPORTING_MAP.each { |header, column| record[column.to_sym] = row[header] }
        end
      end

      upsert_all(records, unique_by: :id)
    end
  end
end

app/models/pokemon_stat.rb
class PokemonStat < ApplicationRecord
  belongs_to :pokemon
  belongs_to :stat

  include Pokemon::Importable

  IMPORTING_MAP = [
    %w[pokemon_id pokemon_id],
    %w[stat_id stat_id],
    %w[base_stat base_stat]
  ].freeze

  IMPORTING_FILE_NAME = 'pokemon_stats.csv'.freeze

  delegate :identifier, to: :stat, prefix: true
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type

  include Pokemon::Importable

  IMPORTING_MAP = [
    %w[pokemon_id pokemon_id],
    %w[type_id type_id],
    %w[slot slot]
  ].freeze

  IMPORTING_FILE_NAME = 'pokemon_types.csv'.freeze
end

app/models/stat.rb
class Stat < ApplicationRecord
  has_many :pokemon_stats
  has_many :pokemons, through: :pokemon_stats

  include Pokemon::Importable

  IMPORTING_MAP = [
    %w[id id],
    %w[identifier identifier],
  ].freeze

  IMPORTING_FILE_NAME = 'stats.csv'.freeze
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types

  include Pokemon::Importable

  IMPORTING_MAP = [
    %w[id id],
    %w[identifier identifier],
  ].freeze

  IMPORTING_FILE_NAME = 'types.csv'.freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  helper_method :current_params

  def index
    @pokemons = Pokemon.where(id: ..1008).preload(:types).with_attached_default_sprite
    if current_params[:name].present?
      @pokemons = @pokemons.joins(:types).where(types: { identifier: downcased_name })
        .or(@pokemons.where("name LIKE ?", "%#{downcased_name}%"))
        .distinct
    end
    @pokemons = set_page_and_extract_portion_from @pokemons.order(:id)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def current_params
    params.permit(:name, :page) || {}
  end

  def downcased_name
    current_params[:name].downcase
  end
end

app/controllers/pwa_controller.rb
class PwaController < ApplicationController
  protect_from_forgery except: :service_worker

  def service_worker
  end

  def manifest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
  def bg_from_type(type)
    {
      normal: "bg-normal",
      fighting: "bg-fighting",
      flying: "bg-flying",
      poison: "bg-poison",
      ground: "bg-ground",
      rock: "bg-rock",
      bug: "bg-bug",
      ghost: "bg-ghost",
      steel: "bg-steel",
      fire: "bg-fire",
      water: "bg-water",
      grass: "bg-grass",
      electric: "bg-electric",
      psychic: "bg-psychic",
      ice: "bg-ice",
      dragon: "bg-dragon",
      dark: "bg-dark",
      fairy: "bg-fairy"
    }[type.identifier.to_sym]
  end

  def abbreviated_stat(pokemon_stat)
    {
      'hp' => 'HP',
      'attack' => 'ATK',
      'defense' => 'DEF',
      'special-attack' => 'SP. ATK',
      'special-defense' => 'SP. DEF',
      'speed' => 'SPD'
    }[pokemon_stat.stat_identifier]
  end

  def stat_percentage(value)
    ((value.to_f / 255) * 100).round
  end
end

app/helpers/pwa_helper.rb
module PwaHelper
end

app/views/home/show.html.erb
<div class="h-screen flex mx-2 sm:mx-0 sm:items-center">
  <div>
    <div class="flex flex-col-reverse sm:flex-row">
      <div class="w-[360px] sm:w-[480px] border-8 border-gray-800 border-b-0 p-2 sm:p-4 rounded-tl-md rounded-tr-md">
        <div class="flex gap-4">
          <div class="rounded-full border-gray-800 border-4 h-12 w-12">
            <div class="rounded-full border-gray-50 border-4 bg-cyan-500 h-full w-full"></div>
          </div>

          <div class="flex gap-1">
            <div class="rounded-full border-gray-800 border-4 bg-red-500 h-4 w-4"></div>
            <div class="rounded-full border-gray-800 border-4 bg-yellow-500 h-4 w-4"></div>
            <div class="rounded-full border-gray-800 border-4 bg-green-500 h-4 w-4"></div>
          </div>
        </div>
      </div>
      <div class="hidden sm:inline-block w-8"></div>
      <div class="flex justify-between items-center grow pl-6 pr-9">
        <div class="w-100 py-4 sm:p-0">
          <h2 class="text-white text-2xl tracking-wider drop-shadow-[4px_4px_rgba(25,25,27,0.5)]"
              style="font-family: 'Press Start 2P', system-ui;">
            PokePedia
          </h2>
          <div class="text-white text-sm opacity-80">
            Made with <span class="text-yellow-300">&hearts;</span> by <a target="_blank" href="https://www.mattbertino.com" class="text-yellow-300 underline hover:text-yellow-400">Matt Bertino</a>
          </div>
        </div>
        <div>
          <button data-controller="pwa-installer"
                  hidden
                  data-action="pwa-installer#install"
                  class="inline-flex items-center gap-x-1.5 rounded-md bg-yellow-300 px-2.5 py-1.5 text-md font-semibold text-gray-800 hover:bg-yellow-400 border-4 border-gray-800 shadow-[8px_8px_rgba(25,25,27,0.5)]">
            <%= render 'icons/download' %>
            <div class="hidden sm:inline-block">
              Install App
            </div>
          </button>
        </div>
      </div>
    </div>

    <div class="flex flex-col sm:flex-row border-8 border-gray-800 border-b-0 sm:border-b-8 sm:shadow-[8px_8px_rgba(25,25,27,0.5)] border-r-0 sm:border-r-8 rounded-b-md sm:rounded-tr-md sm:h-[644px]">
      <div class="w-[352px] sm:w-[464px] h-full border-gray-800 border-r-8 sm:border-none">
        <div class="border-gray-800 p-3 sm:p-6 rounded-md h-[348px] sm:h-full">
          <%= turbo_frame_tag :pokemon_details, src: Pokemon.first %>
        </div>
      </div>

      <div class="hidden sm:inline-block sm:w-8 border-gray-800 border-x-8 relative">
        <div class="absolute top-8 w-full border-t-4 border-gray-800"></div>
        <div class="absolute top-12 w-full border-t-4 border-gray-800"></div>
        <div class="absolute bottom-8 w-full border-t-4 border-gray-800"></div>
        <div class="absolute bottom-12 w-full border-t-4 border-gray-800"></div>
      </div>

      <div class="sm:hidden h-4 border-gray-800 border-4 border-r-8 border-l-0 relative">
        <div class="absolute left-8 h-full border-l-4 border-gray-800"></div>
        <div class="absolute left-12 h-full border-l-4 border-gray-800"></div>
        <div class="absolute right-8 h-full border-l-4 border-gray-800"></div>
        <div class="absolute right-12 h-full border-l-4 border-gray-800"></div>
      </div>

      <div class="w-[352px] sm:w-[464px] h-[644px] sm:h-full border-gray-800 border-r-8 rounded-br-md border-b-8 sm:border-none">
        <div class=" border-gray-800 p-3 sm:p-6 flex flex-col rounded-md gap-4 h-full" data-controller="scroller">
          <%= form_with url: pokemons_path,
            method: :get,
            data: { controller: 'debounce', turbo_frame: "pokemons_page_1" } do |f| %>
            <div class="relative text-gray-40">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <%= render 'icons/search' %>
              </div>
              <%= f.text_field :name,
                placeholder: "Search",
                autocomplete: 'off',
                data: { action: 'input->debounce#search input->scroller#scrollToTop' },
                class: "block w-full rounded-md border-4 border-gray-800 bg-gray-50 py-1.5 pl-10 pr-3 text-gray-900" %>
            </div>
          <% end %>

          <div data-scroller-target="scrollable" class="flex flex-col h-full bg-gray-50 border-gray-800 border-4 rounded-md divide-y divide-gray-400 overflow-y-scroll">
            <%= turbo_frame_tag "pokemons_page_1", src: pokemons_path(page: 1) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/icons/_arrow_right.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
  <path fill-rule="evenodd" d="M3 10a.75.75 0 0 1 .75-.75h10.638L10.23 5.29a.75.75 0 1 1 1.04-1.08l5.5 5.25a.75.75 0 0 1 0 1.08l-5.5 5.25a.75.75 0 1 1-1.04-1.08l4.158-3.96H3.75A.75.75 0 0 1 3 10Z" clip-rule="evenodd" />
</svg>

app/views/icons/_download.html.erb
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
  <path d="M10.75 2.75a.75.75 0 0 0-1.5 0v8.614L6.295 8.235a.75.75 0 1 0-1.09 1.03l4.25 4.5a.75.75 0 0 0 1.09 0l4.25-4.5a.75.75 0 0 0-1.09-1.03l-2.955 3.129V2.75Z" />
  <path d="M3.5 12.75a.75.75 0 0 0-1.5 0v2.5A2.75 2.75 0 0 0 4.75 18h10.5A2.75 2.75 0 0 0 18 15.25v-2.5a.75.75 0 0 0-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5Z" />
</svg>

app/views/icons/_loading.html.erb
<svg  class="inline w-10 h-10 text-gray-300 animate-spin dark:text-gray-600 fill-red-500" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
  <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
</svg>

app/views/icons/_search.html.erb
<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokePedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Player 2 Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">

    <!-- PWA -->
    <link rel="manifest" href="/manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#ef4444"/>
    <link rel="apple-touch-icon" sizes="120x120" href=<%= asset_path("pwa_icons/icon-144x144.png")%>>
    <link rel="apple-touch-icon" sizes="152x152" href=<%= asset_path("pwa_icons/icon-152x152.png")%>>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href=<%= asset_path("favicons/apple-touch-icon.png")%>>
    <link rel="icon" type="image/png" sizes="32x32" href=<%= asset_path("favicons/favicon-32x32.png")%>>
    <link rel="icon" type="image/png" sizes="16x16" href=<%= asset_path("favicons/favicon-16x16.png")%>>
    <link rel="manifest" href= <%= asset_path("favicons/site.webmanifest") %>>
  </head>

  <body class="bg-red-500">
    <div class="container w-[375px] sm:w-[960px] m-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pokemon_stats/_pokemon_stat.html.erb
<%# locals: (pokemon_stat:, pokemon_type:) -%>

<div class="text-xs grid grid-cols-6 py-1">
  <div class="opacity-50"><%= abbreviated_stat(pokemon_stat) %></div>
  <div class="pl-2 opacity-90"><%= pokemon_stat.base_stat %></div>

  <div class="col-span-4">
    <div class="w-full bg-gray-200 rounded-full h-full">
      <div class="<%= bg_from_type(pokemon_type)%> h-full rounded-full" style="width: <%= stat_percentage(pokemon_stat.base_stat) %>%;"></div>
    </div>
  </div>
</div>

app/views/pokemons/_evolution_group.html.erb
<%# locals: (pokemons:) -%>

<div class="flex flex-col gap-2">
  <% pokemons.each do |pokemon| %>
    <%= link_to pokemon do %>
      <%= image_tag cdn_image_url(pokemon.default_sprite), loading: :lazy, class: " h-20" %>
    <% end %>
  <% end %>
</div>

app/views/pokemons/_pokemon.html.erb
<%# locals: (pokemon:) -%>

<%= link_to pokemon, data: { turbo_frame: "pokemon_details" } do %>
  <div class="flex flex-column gap-4 p-4 hover:bg-gray-50 hover:cursor-pointer border-b-2 border-gray-300">
    <div class="grid content-center">
      <%= image_tag cdn_image_url(pokemon.default_sprite), loading: :lazy, class: "h-14" %>
    </div>

    <div class="grow flex justify-between items-center">
      <div class="text-md font-bold opacity-90"><%= pokemon.name.humanize%></div>
      <div><%= render pokemon.types %></div>
    </div>
  </div>
<% end %>

app/views/pokemons/index.html.erb
<%= turbo_frame_tag "pokemons_page_#{@page.number}" do %>
  <%= render @pokemons %>

  <% unless @page.last? %>
    <%= turbo_frame_tag "pokemons_page_#{@page.next_param}",
      loading: :lazy,
      src: pokemons_path(current_params.merge(page: @page.next_param)) do %>
      <div class="text-center py-4">
        <%= render 'icons/loading' %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/pokemons/show.html.erb
<%= turbo_frame_tag :pokemon_details do %>
    <div class="p-4 sm:p-8 flex flex-col gap-4 bg-gray-50 border-gray-800 border-4 rounded-md h-full overflow-y-scroll">
    <div class="grid justify-center relative border-gray-800 border-4 rounded-md">
      <div class="absolute w-full bg-gray-700 rounded-sm h-full"></div>

      <div class="relative">
        <%= image_tag cdn_image_url(@pokemon.default_sprite), loading: :lazy, class: "h-48" %>
      </div>
    </div>

    <div class="flex justify-between items-center">
      <div class="rounded-full border-gray-800 border-4 bg-red-500 h-8 w-8"></div>

      <div class="text-center">
        <div class="text-xs opacity-50 italic">#<%= @pokemon.order.to_s.rjust(4, '0') %></div>
        <div class="text-xl font-bold opacity-90"><%= @pokemon.name.humanize%></div>
        <div class=""><%= render @pokemon.types %></div>
      </div>

      <div class="flex flex-col gap-2 w-8">
        <div class="border-gray-700 border-2 rounded-full"></div>
        <div class="border-gray-700 border-2 rounded-full"></div>
        <div class="border-gray-700 border-2 rounded-full"></div>
      </div>
    </div>

    <div>
      <div class="text-md font-semibold">Description</div>
      <div class="text-sm"><%= @pokemon.description %></div>
    </div>

    <div>
      <div class="text-md font-semibold">Stats</div>
      <%= render @pokemon.pokemon_stats, pokemon_type: @pokemon.pokemon_types.first.type %>
    </div>

    <div>
      <div class="text-md font-semibold">Evolutions</div>
      <div class="flex justify-between items-center">
        <%= render partial: "evolution_group",
                   collection: @pokemon.full_evolution_chain,
                   as: :pokemons,
                   spacer_template: "icons/arrow_right"%>
      </div>
    </div>
  </div>
<% end %>

app/views/types/_type.html.erb
<span class="<%= bg_from_type(type)%> border border-white text-white text-sm font-medium me-2 px-1.5 py-0.5 rounded-lg">
  <%= type.identifier.humanize %>
</span>